### ISSUE TITLE
Failure on installation

### ISSUE THREAD

**Issue by tarngerine** [karaggeorge/kap-camera#1]
Missing module?

```
Something went wrong while loading “kap-camera”
Error: Cannot find module 'electron-util'
Require stack:
- /Users/tarng/Library/Application Support/Kap/plugins/node_modules/kap-camera/index.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (/Users/tarng/Library/Application Support/Kap/plugins/node_modules/kap-camera/index.js:3:14)
```

**Comment by gabrieljordan** [comment]
I also get the install error. If I install another plugin first (such as hide desktop icons), it does NOT give the error an installs... but it never actually works, and in fact, prevents Kap from functioning... Press record and it never starts recording. Kill Kap with Activity Monitor, re-open, disable Camera plugin, and Kap works again.

**Comment by sherlockmac** [comment]
I have the same issue ... Running Kap Version 3.2.2 on macOS 10.15.6
