### ISSUE TITLE
Something went wrong while loading “kap-camera”

### ISSUE THREAD

**Issue by asyraf-labs** [karaggeorge/kap-camera#2]
undefined

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.1

```
Something went wrong while loading “kap-camera”

Error: Cannot find module 'electron-util'
Require stack:
- /Users/amirulasyraf/Library/Application Support/Kap/plugins/node_modules/kap-camera/index.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (/kap-camera/index.js:3:14)
```

**Comment by simpleshadow** [comment]
I was able to install both `kap-camera` and `electron-util` manually, but unable to get the camera to show.

1. Open a terminal.
2. `cd ~/Library/Application Support/Kap/plugins`.
3. `yarn electron-util kap-camera`.
4. Open Kap.
