### ISSUE TITLE
Something went wrong while loading “kap-camera”

### ISSUE THREAD

**Issue by davetoxa** [karaggeorge/kap-camera#33]
undefined

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.2

```
Something went wrong while loading “kap-camera”

Error: Cannot find module 'electron-util'
Require stack:
- /Users/anthony/Library/Application Support/Kap/plugins/node_modules/kap-camera/index.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js
- /Applications/Kap.app/Contents/Resources/app.asar/main/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (/kap-camera/index.js:3:14)
```

**Comment by megaroeny** [comment]
Why is this same issue duplicated so many times in this repo? Should mark all the rest as spam honestly

![image](https://user-images.githubusercontent.com/1559447/101815711-f19a1800-3aed-11eb-84c9-9ed12e6c16da.png)
