### ISSUE TITLE
macOS 12.0.1 & Kap 3.4.1: Camera is not showing up when recording and camera video is not getting recorded

### ISSUE THREAD

**Issue by christianblessing-me** [karaggeorge/kap-camera#44]
- macOS version: 12.0.1
- Kap version: 3.4.1
- Step to reproduce: Activate the Camera Plugin, start the recording
- Current behavior: The camera window is not showing up when recording neither is the camera recorded when playing back the recorded video.
- Expected behavior: The camera window is showing up while recording and the image of the camera is actually getting recorded.
- Workaround: none

I've already checked the camera permission in the privacy settings, I reverted them and set them back. I also already re-installed Kap as well as the kap-camera repository completely but nothing solved the issue.

**Comment by willwillems** [comment]
Some more discussion here: https://github.com/karaggeorge/kap-camera/issues/34 also does not work for me on  12.0.1 with 3.4.1.

**Comment by christianblessing-me** [comment]
Any updates here?

**Comment by willwillems** [comment]
I was contemplating picking this up but it seems like the owner of this repo isn't accepting/merging PR's

**Comment by mbukh** [comment]
macOS version: 12.0.1
Kap version: 3.4.1
still not working

**Comment by remus-b** [comment]
I'm also having issues with this pluging for a few months already. Everything is checked under permissions, even the macOS Monterey shows activity for the camera being used by the Kap app but not showing anywhere during the recording.

**Comment by ankibalyan** [comment]
same behaviour. camera is not working on mac os 12.1 and kap intel Version 3.5.3 (3.5.3.1804)

**Comment by KastanDay** [comment]
Same behavior on MacOS 12.3 with Apple Silicon.

**Comment by ibehnam** [comment]
Can confirm on MBP with M1 Pro.

**Comment by KastanDay** [comment]
Since this repo seems mostly unmaintained, I switched to OBS and I love it. I even made a little matte to make my camera into a circle (instead of a 16x9 rectangle). Good luck!

**Comment by ibehnam** [comment]
> Since this repo seems mostly unmaintained, I switched to OBS and I love it. I even made a little matte to make my camera into a circle (instead of a 16x9 rectangle). Good luck!

I think I'll do the same. OBS runs smoothly on M1. I liked the simplicity of Kap and considered donating to it as well. But at this point it's mostly useful for creating quick gifs and videos, not educational videos with my picture on the screen.

**Comment by Nitrodist** [comment]
This affects me as well, Kap is not working with macOS Monterey 12.4 using an M1.

**Comment by clearlysid** [comment]
Hey people, I've fixed this issue in [my fork](https://github.com/clearlysid/kap-cam) alongside other tweaks I wanted for my use. Haven't published it yet, but you can feel free to clone and use it if you'd like.

**Comment by ibehnam** [comment]
> Hey people, I've fixed this issue in [my fork](https://github.com/clearlysid/kap-cam) alongside other tweaks I wanted for my use. Haven't published it yet, but you can feel free to clone and use it if you'd like.

Can you do a pull request?

**Comment by remus-b** [comment]
> Hey people, I've fixed this issue in [my fork](https://github.com/clearlysid/kap-cam) alongside other tweaks I wanted for my use. Haven't published it yet, but you can feel free to clone and use it if you'd like.

And how can I use it? Did someone test this?

**Comment by proton1k** [comment]
Kap itself has a new build for M1 chip, probably solved issues with capturing screen, but this plugin still does not work with the latest version of Kap, Macbook Air M1 and Monterey 12.6.

**Comment by spy4x** [comment]
Still same issue :(

**Comment by aleksfadini** [comment]
Same. Can someone post a plugin that works or at least point to a different option from within Kap?

**Comment by thunfischbrot** [comment]
For future reference: [This fork works currently](https://github.com/thunfischbrot/kap-cam) and includes the neccessary installation steps in the README.

**Comment by davidscheutz** [comment]
@thunfischbrot awesome man!

However I run into the following issue with your fork at the last step `npm link`:

`npm ERR! Cannot destructure property 'name' of '.for' as it is undefined.`

**Logs**
```
0 verbose cli /usr/local/Cellar/node/21.6.1/bin/node /usr/local/bin/npm
1 info using npm@10.2.4
2 info using node@v21.6.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/davidscheutz/Library/Application Support/Kap/plugins/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/davidscheutz/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing config:load:flatten Completed in 3ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm link
22 verbose argv "link"
23 timing npm:load:setTitle Completed in 5ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/Users/davidscheutz/.npm/_logs/2024-05-18T23_30_27_984Z-
26 verbose logfile /Users/davidscheutz/.npm/_logs/2024-05-18T23_30_27_984Z-debug-0.log
27 timing npm:load:logFile Completed in 11ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 51ms
31 timing config:load:flatten Completed in 1ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 7ms
36 timing idealTree:userRequests Completed in 4ms
37 silly idealTree buildDeps
38 silly placeDep ROOT undefined@ OK for:  want: file:../../../Users/davidscheutz/Library/Application Support/Kap/plugins
39 timing idealTree:#root Completed in 7ms
40 timing idealTree:node_modules/undefined Completed in 0ms
41 timing idealTree:buildDeps Completed in 9ms
42 timing idealTree:fixDepFlags Completed in 1ms
43 timing idealTree Completed in 21ms
44 timing reify:loadTrees Completed in 23ms
45 timing command:link Completed in 40ms
46 verbose stack TypeError: Cannot destructure property 'name' of '.for' as it is undefined.
46 verbose stack     at [diffTrees] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:353:20)
46 verbose stack     at Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:169:27)
46 verbose stack     at async Link.linkPkg (/usr/local/lib/node_modules/npm/lib/commands/link.js:151:5)
46 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
47 verbose cwd /Users/davidscheutz/Library/Application Support/Kap/plugins
48 verbose Darwin 23.4.0
49 verbose node v21.6.1
50 verbose npm  v10.2.4
51 error Cannot destructure property 'name' of '.for' as it is undefined.
52 verbose exit 1
53 timing npm Completed in 288ms
54 verbose unfinished npm timer reify 1716075028233
55 verbose unfinished npm timer reify:diffTrees 1716075028268
56 verbose code 1
57 error A complete log of this run can be found in: /Users/davidscheutz/.npm/_logs/2024-05-18T23_30_27_984Z-debug-0.log

```
PS creating issues isn't enabled for your repo
PPS sprichst du Deutsch? 😎

**Comment by stezz** [comment]
> @thunfischbrot awesome man!
> 
> However I run into the following issue with your fork at the last step `npm link`:
> 
> `npm ERR! Cannot destructure property 'name' of '.for' as it is undefined.`


Yeah same problem here, @thunfischbrot any hint how to fix that if that worked for you ?

**Comment by thunfischbrot** [comment]
Hi! To make sure I can reproduce this issue, please try the following steps and let me kow if you still experience the same issues:

1. Open your terminal and enter the following command to download and make available the plugin to kap:

```
cd ~/Library/Application\ Support/Kap/plugins/
npm remove kap-camera
npm remove kap-cam
git clone https://github.com/thunfischbrot/kap-cam
cd kap-cam
npm link
cd ..
npm install ./kap-cam
npm link
```

2. Open Kap `Preferences`
3. Select the `Plugins` pane, and switch to `Discover` tab.
4. In the list of plugins, find `cam` and toggle it on.

**Comment by stezz** [comment]
Hi @thunfischbrot, thanks for the quick reply. Unfortunately `cam` does not appear in the plugins/Discover tab because `npm link` fails.

```
> plugins % npm remove kap-camera


changed 1 package, and audited 102 packages in 413ms

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
> plugins % npm remove kap-cam


removed 75 packages, and audited 27 packages in 404ms

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
> plugins % git clone https://github.com/thunfischbrot/kap-cam

Cloning into 'kap-cam'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 151 (delta 77), reused 113 (delta 49), pack-reused 0
Receiving objects: 100% (151/151), 65.03 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (77/77), done.
> plugins % cd kap-cam

> kap-cam % npm link

up to date, audited 3 packages in 366ms

found 0 vulnerabilities
> kap-cam % cd ..

> plugins % npm install ./kap-cam


added 75 packages, and audited 102 packages in 1s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
> plugins % npm link

npm error Cannot destructure property 'name' of '.for' as it is undefined.

npm error A complete log of this run can be found in: /Users/myuser/.npm/_logs/2024-06-08T12_36_40_948Z-debug-0.log
> plugins % cat /Users/myuser/.npm/_logs/2024-06-08T12_36_40_948Z-debug-0.log
0 verbose cli /opt/homebrew/Cellar/node/22.2.0/bin/node /opt/homebrew/bin/npm
1 info using npm@10.7.0
2 info using node@v22.2.0
3 silly config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc
4 silly config:load:file:/Users/myuser/Library/Application Support/Kap/plugins/.npmrc
5 silly config:load:file:/Users/myuser/.npmrc
6 silly config:load:file:/opt/homebrew/etc/npmrc
7 verbose title npm link
8 verbose argv "link"
9 verbose logfile logs-max:10 dir:/Users/myuser/.npm/_logs/2024-06-08T12_36_40_948Z-
10 verbose logfile /Users/myuser/.npm/_logs/2024-06-08T12_36_40_948Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly placeDep ROOT undefined@ OK for:  want: file:../../../Users/myuser/Library/Application Support/Kap/plugins
15 verbose stack TypeError: Cannot destructure property 'name' of '.for' as it is undefined.
15 verbose stack     at [diffTrees] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:427:20)
15 verbose stack     at Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:141:27)
15 verbose stack     at async Link.linkPkg (/opt/homebrew/lib/node_modules/npm/lib/commands/link.js:147:5)
15 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
16 verbose cwd /Users/myuser/Library/Application Support/Kap/plugins
17 verbose Darwin 23.5.0
18 verbose node v22.2.0
19 verbose npm  v10.7.0
20 error Cannot destructure property 'name' of '.for' as it is undefined.
21 verbose exit 1
22 verbose code 1
23 silly unfinished npm timer reify 1717850201053
24 silly unfinished npm timer reify:diffTrees 1717850201063
25 error A complete log of this run can be found in: /Users/myuser/.npm/_logs/2024-06-08T12_36_40_948Z-debug-0.log
```

**Comment by subodhss23** [comment]
any updates yet?

**Comment by algebraic-al** [comment]
Guys, I've managed to get it working, thanks to ChatGPT :)

CC: @davidscheutz @stezz  @subodhss23 

Below is a step‐by‐step guide in English that helped resolve the issue. It explains how to register the plugin correctly so that it appears in Kap’s Discover tab. Feel free to share this with others facing similar problems.

---

### Problem Overview

A user reported that after following these commands:

```bash
cd ~/Library/Application\ Support/Kap/plugins/
npm remove kap-camera
npm remove kap-cam
git clone https://github.com/thunfischbrot/kap-cam
cd kap-cam
npm link
cd ..
npm install ./kap-cam
npm link
```

the plugin never appeared in the **Plugins → Discover** tab in Kap. The error encountered was:

```
npm error Cannot destructure property 'name' of '.for' as it is undefined.
```

A look at the logs revealed that the error came from the `npm link` command. The root cause turned out to be two things:
1. **The plugin’s package.json lacked a proper registration section for Kap.**
2. **The main Kap plugins manifest wasn’t registering the plugin as a dependency.**

---

### Step-by-Step Fix

#### 1. Remove Any Previous Versions  
To ensure a clean installation, remove any previous instances:
```bash
cd ~/Library/Application\ Support/Kap/plugins/
rm -rf kap-cam
```

#### 2. Clone the Plugin Repository  
Clone the latest version from GitHub:
```bash
git clone https://github.com/thunfischbrot/kap-cam
```

#### 3. Update the Plugin’s package.json  
Open the file:
```bash
subl "~/Library/Application Support/Kap/plugins/kap-cam/package.json"
```
  
Add the following block at the end (just before the closing curly brace) to register the plugin with Kap:
```json
,
"kapPlugin": {
  "name": "kap-cam",
  "description": "Loom-like webcam overlay for Kap",
  "main": "index.js"
}
```
  
Your final `package.json` should look like this:
```json
{
  "name": "kap-cam",
  "version": "1.0.1",
  "description": "Loom-like webcam overlay for Kap",
  "repository": "clearlysid/kap-cam",
  "license": "MIT",
  "author": {
    "name": "Siddharth",
    "email": "siddharth99c@gmail.com",
    "url": "https://www.sid.me"
  },
  "keywords": [
    "kap-plugin",
    "camera",
    "webcam",
    "recording",
    "loom"
  ],
  "kap": {
    "version": ">=3.3.2"
  },
  "scripts": {
    "build-devices": "swiftc -o ./binaries/devices -target 'x86_64-apple-macosx10.14' ./binaries/devices.swift",
    "build-permissions": "swiftc -o ./binaries/permissions -target 'x86_64-apple-macosx10.14' ./binaries/permissions.swift",
    "build": "yarn run build-devices && yarn run build-permissions"
  },
  "peerDependencies": {
    "electron": "*"
  },
  "dependencies": {
    "electron-util": "^0.14.2",
    "execa": "^4.0.3"
  },
  "kapPlugin": {
    "name": "kap-cam",
    "description": "Loom-like webcam overlay for Kap",
    "main": "index.js"
  }
}
```
  
Save the file.

#### 4. Reinstall and Link the Plugin  
Next, reinstall the dependencies and link the plugin:
```bash
cd "~/Library/Application Support/Kap/plugins/kap-cam"
rm -rf node_modules package-lock.json  # Clean old installs
npm install
npm link
```

Then, register the plugin in the main plugins manifest:
```bash
cd "~/Library/Application Support/Kap/plugins/"
```

Check the main manifest file:
```bash
cat package.json
```
  
If it shows:
```json
{
  "dependencies": {}
}
```
  
Update it to include the plugin by adding:
```json
{
  "dependencies": {
    "kap-cam": "latest"
  }
}
```
  
You can edit the file with Sublime:
```bash
subl "~/Library/Application Support/Kap/plugins/package.json"
```
  
Or use this command to add the dependency:
```bash
sed -i '' 's/"dependencies": {/"dependencies": {\n    "kap-cam": "latest",/' "~/Library/Application Support/Kap/plugins/package.json"
```

Finally, run:
```bash
npm link
```
  
This should update the plugin registration.

#### 5. Restart Kap  
Quit Kap completely (use Cmd + Q) and then restart it.  
  
Open **Kap Preferences → Plugins → Discover**. The `kap-cam` (often listed as “cam”) should now appear. Toggle it on to activate.

---

### Final Note

The issue was resolved by ensuring that both the plugin’s own package.json has a proper `"kapPlugin"` section and that the main plugins manifest in `~/Library/Application Support/Kap/plugins/package.json` registers the plugin as a dependency (`"kap-cam": "latest"`).

If the plugin still does not appear, check the developer console in Kap (Cmd + Option + I) for any errors. This guide should help others facing the same issue.

Happy recording!

**Comment by tonglil** [comment]
To fix the `npm link` issue, make sure the `package.json` file has a `name` field.
Mine looked something like this.

```
{
  "name": "plugins",
  "dependencies": {
    "kap-cam": "latest"
  }
}
```
